# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\demo_layout.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QLineEdit, QCompleter
from PyQt5.QtCore import Qt

from PyQt5.QtWidgets import QApplication, QHBoxLayout, QWidget, QPushButton
from PyQt5.QtCore import Qt, QMimeData, pyqtSignal
from PyQt5.QtGui import QDrag
from PyQt5.QtGui import QDrag, QPixmap
from PyQt5.QtWidgets import QApplication, QHBoxLayout, QWidget, QLabel, QMainWindow, QVBoxLayout
from PyQt5.QtCore import Qt, QMimeData, pyqtSignal
from PyQt5.QtGui import QDrag, QPixmap

class DragButton(QPushButton):
    def mouseMoveEvent(self, e):
        if e.buttons() == Qt.LeftButton:
            drag = QDrag(self)
            mime = QMimeData()
            drag.setMimeData(mime)

            pixmap = QPixmap(self.size())
            self.render(pixmap)
            drag.setPixmap(pixmap)

            drag.exec_(Qt.MoveAction)

encryption_functions = ["sss", "s", "sora", "Base54", "Base64", "Base48", "stext", "sssora", "Heater", "Stove", "Living Room Light", "Balcony Light", "Fan", "Room Light", "Oven", "Desk Light", "Bedroom Heater", "Wall Switch", 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q']
all_btns = []

class Ui_main_window(object):

    def setupUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate

        main_window.setObjectName("main_window")
        main_window.resize(1113, 774)
        font = QtGui.QFont()
        font.setPointSize(12)
        main_window.setFont(font)
        main_window.setLayoutDirection(QtCore.Qt.LeftToRight)
        main_window.setTabShape(QtWidgets.QTabWidget.Rounded)
        
        self.centralwidget = QtWidgets.QWidget(main_window)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        
        self.names_action_btn_H = QtWidgets.QHBoxLayout()
        self.names_action_btn_H.setContentsMargins(0, 5, 0, 5)
        self.names_action_btn_H.setObjectName("names_action_btn_H")
        
        self.operations_2 = QtWidgets.QLabel(self.centralwidget)
        self.operations_2.setObjectName("operations_2")
        
        self.names_action_btn_H.addWidget(self.operations_2, 1)
        
        self.Refresh = QtWidgets.QPushButton(self.centralwidget)
        self.Refresh.setFlat(True)
        self.Refresh.setIcon(QtGui.QIcon('refresh.png'))
        self.Refresh.setIconSize(QtCore.QSize(24,24))
        self.Refresh.setObjectName("Refresh")
        
        self.names_action_btn_H.addWidget(self.Refresh, 1)
        
        self.Recipe = QtWidgets.QLabel(self.centralwidget)
        self.Recipe.setObjectName("Recipe")
        
        self.names_action_btn_H.addWidget(self.Recipe, 2)
        
        self.recipe_del = QtWidgets.QPushButton(self.centralwidget)
        self.recipe_del.setFlat(True)
        self.recipe_del.setIcon(QtGui.QIcon('delete.png'))
        self.recipe_del.setIconSize(QtCore.QSize(24,24))
        self.recipe_del.setObjectName("recipe_del")
        
        self.names_action_btn_H.addWidget(self.recipe_del, 2)
        
        self.Input = QtWidgets.QLabel(self.centralwidget)
        self.Input.setObjectName("Input")
        
        self.names_action_btn_H.addWidget(self.Input, 2)
        
        self.open_file_input = QtWidgets.QPushButton(self.centralwidget)
        self.open_file_input.setFlat(True)
        self.open_file_input.setIcon(QtGui.QIcon('folder.png'))
        self.open_file_input.setIconSize(QtCore.QSize(24,24))
        self.open_file_input.setObjectName("open_file_input")
        
        self.names_action_btn_H.addWidget(self.open_file_input, 1)
        
        self.input_del = QtWidgets.QPushButton(self.centralwidget)
        self.input_del.setFlat(True)
        self.input_del.setIcon(QtGui.QIcon('delete.png'))
        self.input_del.setIconSize(QtCore.QSize(24,24))
        self.input_del.setObjectName("input_del")
        
        self.names_action_btn_H.addWidget(self.input_del, 1)
        
        self.verticalLayout.addLayout(self.names_action_btn_H)
        
        self.main_layout = QtWidgets.QHBoxLayout()
        self.main_layout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.main_layout.setContentsMargins(0, 0, 0, -1)
        self.main_layout.setSpacing(0)
        self.main_layout.setObjectName("main_layout")
        
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, 0, 0, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        
        self.search_bar_vertical = QtWidgets.QVBoxLayout()
        self.search_bar_vertical.setContentsMargins(0, 5, -1, 20)
        self.search_bar_vertical.setObjectName("search_bar_vertical")
        
        self.search = QLineEdit(self.centralwidget)
        self.search.setPlaceholderText("Search...")
        self.search.textChanged.connect(self.search_enc_algorithm_update)
        self.search.setObjectName("search")
        self.search_bar_vertical.addWidget(self.search)
        
        self.verticalLayout_4.addLayout(self.search_bar_vertical)
        
        self.operations = QtWidgets.QScrollArea(self.centralwidget)
        self.operations.setEnabled(True)
        self.operations.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.operations.setAutoFillBackground(False)
        self.operations.setWidgetResizable(True)
        self.operations.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.operations.setObjectName("operations")
        
        self.all_operations_scroll = QtWidgets.QWidget()
        self.all_operations_scroll.setGeometry(QtCore.QRect(0, 0, 343, 804))
        self.all_operations_scroll.setObjectName("all_operations_scroll")

        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.all_operations_scroll)
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        for i, l in enumerate(encryption_functions):
            self.btn = DragButton(self.all_operations_scroll)

            self.btn.setFlat(True)
            self.btn.setStyleSheet(
                "QPushButton"
                "{"
                    "color: #002B5B;"
                    "background-color: #cce4ff;"
                    "padding-left: 20px;"
                    "padding-top: 9px;"
                    "padding-bottom: 10px;"
                    "border: 2px solid #cce4ff;"
                    "border-radius: 5px;"
                    "font-size: 15px;"
                    "font-weight: bold;"
                    "text-align: left;"
                "}"
            )

            self.btn.setObjectName(l)
            self.btn.setText(_translate("main_window", l + "_" + str(i)))
            
            all_btns.append(self.btn)

            self.verticalLayout_2.addWidget(self.btn)

        self.completer = QCompleter(encryption_functions)
        self.completer.setCaseSensitivity(Qt.CaseInsensitive)
        self.search.setCompleter(self.completer)

        self.operations.setWidget(self.all_operations_scroll)
        self.verticalLayout_4.addWidget(self.operations)
        self.main_layout.addLayout(self.verticalLayout_4, 2)
        
        self.recipe = QtWidgets.QScrollArea(self.centralwidget)
        self.recipe.setWidgetResizable(True)
        self.recipe.setObjectName("recipe")

        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 363, 709))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setContentsMargins(0, 0, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        
        self.recipe.setWidget(self.scrollAreaWidgetContents)
        self.main_layout.addWidget(self.recipe, 4)
        
        self.input_output = QtWidgets.QVBoxLayout()
        self.input_output.setContentsMargins(0, -1, 0, -1)
        self.input_output.setObjectName("input_output")
        
        self.input = QtWidgets.QTextBrowser(self.centralwidget)
        self.input.setObjectName("input")
        
        self.input_output.addWidget(self.input)
        
        self.output_actions = QtWidgets.QHBoxLayout()
        self.output_actions.setContentsMargins(-1, 5, -1, 5)
        self.output_actions.setObjectName("output_actions")
        
        self.output_2 = QtWidgets.QLabel(self.centralwidget)
        self.output_2.setObjectName("output_2")
        
        self.output_actions.addWidget(self.output_2, 2)
        
        self.open_output = QtWidgets.QPushButton(self.centralwidget)
        self.open_output.setFlat(True)
        self.open_output.setIcon(QtGui.QIcon('folder.png'))
        self.open_output.setIconSize(QtCore.QSize(24,24))
        self.open_output.setObjectName("open_output")
        
        self.output_actions.addWidget(self.open_output, 1)
        
        self.output_del = QtWidgets.QPushButton(self.centralwidget)
        self.output_del.setFlat(True)
        self.output_del.setIcon(QtGui.QIcon('delete.png'))
        self.output_del.setIconSize(QtCore.QSize(24,24))
        self.output_del.setObjectName("output_del")
        
        self.output_actions.addWidget(self.output_del, 1)
        self.input_output.addLayout(self.output_actions)
        
        self.output = QtWidgets.QTextBrowser(self.centralwidget)
        self.output.setObjectName("output")
        
        self.input_output.addWidget(self.output)
        self.main_layout.addLayout(self.input_output, 4)
        self.verticalLayout.addLayout(self.main_layout)
        
        main_window.setCentralWidget(self.centralwidget)

        main_window.setWindowTitle(_translate("main_window", "MainWindow"))
        self.operations_2.setText(_translate("main_window", "Operations"))
        self.Recipe.setText(_translate("main_window", "Recipe"))
        self.Input.setText(_translate("main_window", "Input"))
        self.input.setHtml(_translate("main_window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
        "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
        "p, li { white-space: pre-wrap; }\n"
        "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
        "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">byte_1234</p></body></html>"))
        self.output_2.setText(_translate("main_window", "output"))
        self.output.setHtml(_translate("main_window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
        "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
        "p, li { white-space: pre-wrap; }\n"
        "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
        "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">hello world</p></body></html>"))

        QtCore.QMetaObject.connectSlotsByName(main_window)

    def search_enc_algorithm_update(self, text):
        for widget in all_btns:
            if text.lower() in widget.objectName().lower():
                widget.show()
            else:
                widget.hide()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_window = QtWidgets.QMainWindow()
    ui = Ui_main_window()
    ui.setupUi(main_window)
    main_window.show()
    sys.exit(app.exec_())
